---
title: "Project2"
author: "Gladies Huilin"
date: "4/19/2020"
output: word_document
---

```{r}
library(MASS)
library(dplyr)
library(ggplot2)
library(caret)
library(nnet)
dataset<-read.table("HaitiPixels_good.txt", header=TRUE, sep= "" )
dim(dataset)
dataset
```

```{r}
library(caTools)
set.seed(3000)
smp_siz = floor(0.75*nrow(dataset))
smp_siz
```
CV
```{r}
set.seed(123)  
train_ind = sample(seq_len(nrow(dataset)),size = smp_siz) 
Train =dataset[train_ind,] 
Test=dataset[-train_ind,] 
```

```{r}
glm_mod = train(
  form = Type ~ .,
  data = Train,
  trControl = trainControl(method = "cv", number = 10),
  method = "glm",
  family = "binomial"
)
```
```{r}
glm_mod 
```

```{r}
glm_mod$results
```

```{r}
glm_mod$finalModel
```

```{r}
summary(glm_mod)
```

```{r}
glm_mod
confusionMatrix(glm_mod)
# generate predictions on hold back data
trainPredicted <- predict(glm_mod,Test)
# generate confusion matrix for hold back data
confusionMatrix(trainPredicted,reference=Test$Type)
```
## hold out data
```{r}
set.seed(2020)
in_train <- createDataPartition(dataset$Type, p = 4/5, list = FALSE)
training <- dataset[ in_train,]
training <- dataset[ in_train,]
```

```{r}
glm_fit <- train(Type ~ ., data = training, method = "glm")
glm_fit
```

```{r}
glm_fit
confusionMatrix(glm_fit)
# generate predictions on hold back data
trainPredicted <- predict(glm_fit,Test)
# generate confusion matrix for hold back data
confusionMatrix(trainPredicted,reference=Test$Type)
```

