---
title: "Project2"
author: "Gladies Huilin"
date: "4/19/2020"
output: word_document
---

```{r}
library(MASS)
library(dplyr)
library(ggplot2)
library(caret)
library(nnet)
dataset<-read.table("HaitiPixels_good.txt", header=TRUE, sep= "" )
dim(dataset)
dataset
```

CV
```{r}
library(caTools)
set.seed(3000)
smp_siz = floor(0.75*nrow(dataset))
smp_siz
```
https://stackoverflow.com/questions/46816174/confusion-matrix-for-random-forest-in-r-caret

```{r}
set.seed(123)  
train_ind = sample(seq_len(nrow(dataset)),size = smp_siz) 
Train =dataset[train_ind,] 
Test=dataset[-train_ind,] 
```

```{r}
memory.limit()
```

```{r}
memory.limit(40000)
```

```{r}
model_rf  <- train(Type~., tuneLength = 3, data = dataset, method = 
                       "rf", importance = TRUE,
                   trControl = trainControl(method = "cv",
                                            number = 5,
                                            savePredictions = "final",
                                            classProbs = T))
```

